In [1]:
import Carthesian_math_package

import Q2

import Q4

import Q5

import Q6

import Loadfile

from math import cos
from math import sin
from math import pi
from math import sqrt
import numpy as np
import os

ModuleNotFoundError: No module named 'Loadfile'

In [4]:
def main():
    """
    Runs the program on "unknown" input identified by character given as argument.
    Writes equivalent output file and prints results.
    """
    np.set_printoptions(precision=2, suppress=True)
 
    char = input('Enter letter of unknown file');
    path = "data/pa1-unknown-"
    calbodyFile = path+char+"-calbody.txt"
    calreadingsFile = path+char+"-calreadings.txt"
    EMPivotFile = path+char+"-empivot.txt"
    optPivotFile = path+char+"-optpivot.txt"
    outputFile = path+char+"-output1.txt"
    
    Cexp = Q4.distortion_calibration(calbodyFile, calreadingsFile)
    print("expected values for C:")
    print(Cexp)
    EMprobe = Q5.EM_pivot(EMPivotFile)[1].T
    print("Location of dimple using EM tracker:")
    print(EMprobe)
    optprobe = Q6.Optical_EM_pivot(optPivotFile, calbodyFile).T
    print("Location of dimple using optical tracker:")
    print(optprobe)
    Loadfile.writeOutput1(outputFile, Cexp,  EMprobe, optprobe)
    print("Writing output to " + outputFile)
    return


if __name__ == '__main__':
    main()


Enter letter of unknown fileh
expected values for C:
[[[210.11 210.75 211.57 209.88 451.48 451.63 450.91 450.01]
  [210.45 210.19 214.31 207.34 453.85 447.95 451.54 446.76]
  [210.8  209.63 217.05 204.79 456.22 444.27 452.16 443.51]
  [209.14 209.53 208.05 209.24 452.   449.39 449.36 450.58]
  [209.48 208.97 210.79 206.69 454.37 445.7  449.99 447.33]
  [209.82 208.41 213.53 204.15 456.74 442.02 450.62 444.09]
  [208.16 208.31 204.53 208.59 452.52 447.14 447.82 451.16]
  [208.51 207.75 207.27 206.04 454.89 443.45 448.44 447.91]
  [208.85 207.2  210.02 203.5  457.26 439.77 449.07 444.66]
  [335.1  335.74 336.49 334.85 576.45 576.56 575.9  574.96]
  [335.45 335.18 339.23 332.31 578.82 572.88 576.53 571.71]
  [335.79 334.62 341.97 329.77 581.19 569.2  577.15 568.47]
  [334.13 334.52 332.97 334.21 576.98 574.31 574.35 575.54]
  [334.48 333.97 335.71 331.66 579.35 570.63 574.98 572.29]
  [334.82 333.41 338.45 329.12 581.72 566.95 575.61 569.04]
  [333.16 333.31 329.45 333.56 577.5  572.06 57